spring:
  profiles:
    active:
      - dev

---
server:
  port: 9527
spring:
  application:
    name: MICROSERVICE-ZUUL-GATEWAY
  profiles: dev
eureka:
  client:
    service-url:
      defaultZone: http://localhost:7001/eureka/
  instance:
    instance-id:  gateway-9527.com #可要可不要
    prefer-ip-address: true
zuul:
  prefix: "/aigou"
  ignored-services: "*"
  routes:
      plat.serviceId: plat-server
      plat.path: /plat/**

---
server:
  port: 9528
spring:
  application:
    name: MICROSERVICE-ZUUL-GATEWAY-TEST
eureka:
  client:
    service-url:
      defaultZone: http://localhost:7001/eureka/
  instance:
    instance-id:  gateway-9528.com #可要可不要
    prefer-ip-address: true
zuul:
  prefix: "/aigou"
  ignored-services: "*"
  routes:
      plat.serviceId: plat-server
      plat.path: /plat/**
